import type { Metadata } from "next";
import "./globals.css";
import { camingoDosProCdRegular } from "@/components/fonts";
import { getSession } from "next-auth/react";
import Providers from "./providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();

	return (
		<html lang="en">
			<body className={`${camingoDosProCdRegular.className}`}>
				<Providers session={session}>
					{children}
				</Providers>
			</body>
		</html>
	);
}
