import type { Metadata } from "next";
import "@/src/app/globals.css";
import { camingoDosProCdRegular } from "@/src/components/fonts";
import { getSession } from "next-auth/react";
import Providers from "@/src/app/providers";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const session = await getSession();

	return (
		<html lang={locale}>
			<body className={`${camingoDosProCdRegular.className}`}>
				<Providers session={session}>{children}</Providers>
			</body>
		</html>
	);
}
